### ISSUE TITLE
kafka_host, kafka_hosts and kafka_ports options

### ISSUE THREAD

**Issue by 90yukke** [karafka/waterdrop#10]
The problem is that Karafka and Waterdrop requires options in different format. Karafka wants options in this format:
```
config.kafka_hosts = ["123.123.123.23:9092"]
```

and waterdrop in this one:
```
config.kafka_host = "123.123.123.23"
config.kafka_ports = ["9092"]
```

I feel that it's not unified enough and there should be the same option names and structure. Then I'd be able to use the same settignslogic namespace for both karafka and waterdrop.

**Comment by mensfeld** [comment]
Done - example app will be updated in few minutes
