### ISSUE TITLE
Add some basic validations of the kafka scope of the config

### ISSUE THREAD

**Issue by mensfeld** [karafka/waterdrop#113]
Unfortunately, we need to add basic rdkafka validations as for seed brokers, those fail silently async.

Let's start simple: seed brokers should have a format like so: `host1:9092,host2:9092,192.168.1.2:9091`. String with coma separated hosts with ports

**Comment by Azdaroth** [comment]
Unless someone really feels like taking it over, I'm gonna handle it during the upcoming weekend ;)

**Comment by mensfeld** [comment]
Go for it. There is already schema for the root scope so you can use it as an example.

I will be working on improving the statistics callback data soon as well. Thank you in advance!
