### ISSUE TITLE
Ability to validate successful responder call

### ISSUE THREAD

**Issue by nickoliver86** [karafka/waterdrop#117]
## Is your feature request related to a problem? Please describe.

I want the ability to confirm that a message was successfully produced to the topic on the broker. I don't care or want to rely on an acknowledgement from a downstream consumer. I simply wish to know if I successfully posted in the first place with some sort of return value or callback. It looks like neither responders nor WaterDrop::SyncProducer provide return values to validate the successful delivery of your message to the topic.

## Describe the solution you'd like

Consider the scenario where perhaps the topic does not exist or there's an ACL error, etc. 

**Topic does not exist:**
```
irb(main):001:0> WaterDrop::SyncProducer.call({'test' => 'test'}.to_json, topic: 'not.a.real.topic')
I, [2019-11-21T17:05:45.387698 #2436]  INFO -- : New topics added to target list: not.a.real.topic
I, [2019-11-21T17:05:45.388066 #2436]  INFO -- : Fetching cluster metadata from kafka://broker.kafka:9093
I, [2019-11-21T17:05:51.377430 #2436]  INFO -- : Discovered cluster metadata; nodes: broker2.kafka:9093 (node_id=218), broker3.kafka:9093 (node_id=254), broker1.kafka:9093 (node_id=175)
E, [2019-11-21T17:05:51.378117 #2436] ERROR -- : Failed to assign partitions to 1 messages in not.a.real.topic
W, [2019-11-21T17:05:51.378265 #2436]  WARN -- : Failed to send all messages to ; attempting retry 1 of 2 after 1s
I, [2019-11-21T17:05:52.380422 #2436]  INFO -- : Fetching cluster metadata from kafka://broker.kafka:9093
I, [2019-11-21T17:05:52.692198 #2436]  INFO -- : Discovered cluster metadata; nodes: broker3.kafka:9093 (node_id=254), broker2.kafka:9093 (node_id=218), broker1.kafka:9093 (node_id=175)
I, [2019-11-21T17:05:52.692766 #2436]  INFO -- : Sending 1 messages to broker1.kafka:9093 (node_id=175)
=> nil
```
We can see above that ruby kafka logs out some useful information denoting that the message fails to send. But functionality which should behave one way or another based on _if_ the message successfully sent, has no way to rollback if this is the case. Ideally I'd want something to the effect of: 

```
ActiveRecord::Base.transaction do
  # modify some local data

  # notify downstream services of this change
  responder_call = Responders::MyCoolResponder.call(message)
  
  # rollback i.e. do not commit local changes if unable to publish message for downstream 
  consumption
  raise ActiveRecord::Rollback unless responder_call.successful?
end
```

## Describe alternatives you've considered

I could in theory convert this to a fully async process which then waits for the consuming service to publish an acknowledgement message to a topic I consume from. But in a workflow like this I don't actually care or need to take action based on the downstream systems receiving it. I simply wish to know that I posted the original message to a topic for their consumption. The current error handling for responders as I understand it protects against responding to a topic which has not been registered or total broker failures but not whether or not you can successfully produce a message in an `acks=all` model.

**Comment by nickoliver86** [comment]
@mensfeld I appreciate the quick response! We're currently pinned to Karafka 1.2 as 1.3 resulted in breaking changes. This is yet another reason for us to resolve and upgrade. Thanks again 👍

**Comment by mensfeld** [comment]
> I appreciate the quick response!

@nickoliver86 dunno if that was irony or not :thinking: ;) took me a while as I had sick leave.

Sorry for the fact, that `1.3` has breaking changes :( I do my best to keep as much of the backward compatibility and the API intact but that is not always an option :(

In case you didn't see: https://mensfeld.pl/2019/09/karafka-framework-1-3-0-release-notes-ruby-kafka/ - you can also reach out to me in case you need any help in the upgrade process.

I highly recommend upgrading to `1.3` as I plan to release Waterdrop `2.0` and make a patch to make it work with Karafka `1.3` (while Karafka `2.0` is under construction).

**Comment by nickoliver86** [comment]
@mensfeld no sarcasm intended! We built a fair amount of application specific abstraction on top of Karafka’s base classes. I’ll make it a priority to upgrade to 1.3 as there is other functionality we’re eager to make use of. I appreciate the support, I’ll reach out if we have any issues 👍
