### ISSUE TITLE
Add an ability to use user-defined parsers for a messages

### ISSUE THREAD

**Issue by agwozdowski** [karafka/waterdrop#12]
Similar issue exists in karafka
https://github.com/karafka/karafka/issues/16

**Comment by mensfeld** [comment]
Now you need to provide a casting on your own:

```ruby
message = WaterDrop::Message.new('topic', 'message')
message.send!

message = WaterDrop::Message.new('topic', { user_id: 1 }.to_json)
message.send!
```

we don't do to_json or anything else on our own. This was breaking binary and some other data formats.
