### ISSUE TITLE
Motivation/example

### ISSUE THREAD

**Issue by ioquatix** [karafka/waterdrop#132]
Sometimes when you look at a project with very little context, you want to know what problem it solves from 1000 meters (metaphor).

I sometimes add a "Motivation" section which explains what problem I was trying to solve, and sometimes include a short example of code in the usage, e.g. here is a particular problem you can solve and here is the code to do it. Not just a single line, but an actual working script.

Finally people coming to your project may not know what Kafka is (I don't). So linking to it and explaining it in half a sentence could be great, e.g.

> Waterdrop is a messaging system for Kafka (link), which is an open source job processing tool.

**Comment by ioquatix** [comment]
> Gem used to send messages to Kafka in an easy way with an extra validation layer. It is a part of the Karafka ecosystem.

Why is it easy? Easier than what? What does the validation layer help with? Why is that relevant?

etc :)

**Comment by ioquatix** [comment]
You shared a video on youtube. You can embed the image link to it too :)

**Comment by mensfeld** [comment]
@ioquatix I will close this issue. I will be writing extensive new docs to Karafka 2.0 and I will include your questions :pray:

**Comment by ioquatix** [comment]
Awesome!
