### ISSUE TITLE
Error when adding batch.size configuration

### ISSUE THREAD

**Issue by katpadi** [karafka/waterdrop#189]
I am trying to set `batch.size` that is based on [librdkafka's configuration](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md). However, I am getting unknown configuration error. 

Any plans on upgrading to [librdkafka v1.5.0](https://github.com/edenhill/librdkafka/blob/master/CHANGELOG.md#librdkafka-v150)? Of course I am assuming this would mean rdkafka should do the upgrade.

**Comment by mensfeld** [comment]
I don't see bigger issues in upgrading this. Will look into that in the upcoming week.

**Comment by mensfeld** [comment]
I've pinged rdkafka ppl. If they do not respond soon, I will fork the repo and release it with updates on my own.

**Comment by mensfeld** [comment]
Hey @katpadi. It has been updated. I will make a release today, tops tomorrow.

**Comment by mensfeld** [comment]
Feel free to use master or update rdkafka directly. Both should work. Closing.
