### ISSUE TITLE
waterdrop-2.1.0 in rubygems & waterdrop-2.0.7 in the repo

### ISSUE THREAD

**Issue by ojab** [karafka/waterdrop#226]
rubygems says that [2.1.0 was released](https://rubygems.org/gems/waterdrop/versions/2.1.0) on 3rd Jan and looks like corresponding commit is https://github.com/karafka/waterdrop/commit/cff782a15c6f0fbcc3bcf25bc45f6d894eb58216, but there isn't a tag and/or GH release for that.

**Comment by mensfeld** [comment]
O shit true. How did I miss that.

**Comment by mensfeld** [comment]
fixed. https://github.com/karafka/waterdrop/releases/tag/v2.1.0 thank you
