### ISSUE TITLE
Missing config options

### ISSUE THREAD

**Issue by ankitagupta12** [karafka/waterdrop#32]
waterdrop documentation has options to setup kafka.ssl.ca_cert and kafka.ssl.client_cert, but Waterdrop::Config is missing these options under setting :kafka. it only allows setting kafka.hosts as a result.

This raises an error in the waterdrop config initializer:

```
/config/initializers/waterdrop.rb:7:in `block in <top (required)>': undefined method `ssl' for #<#<Class:0x007fd3912c0580>:0x007fd3912c0350> (NoMethodError)
```

**Comment by mensfeld** [comment]
Creepy - we were talking about that yesterday with @agwozdowski 
We're fixing this here: https://github.com/karafka/karafka/issues/160 but if you need it asap, feel free to PR a quick patch. It seems we broke it somewhere down the road :(

**Comment by ankitagupta12** [comment]
yeah we just happened to discover it yesterday. okay i can create a quick patch just in case it becomes a blocker for us

**Comment by mensfeld** [comment]
@ankitagupta12 great. Looking forward to it then. It should be a fairly simple change.

**Comment by mensfeld** [comment]
@ankitagupta12 any update on that one?

**Comment by mensfeld** [comment]
This already been fixed.
