### ISSUE TITLE
Not seeing librdkafka 2.0.2 in karafka-rdkafka 0.12.1?

### ISSUE THREAD

**Issue by samsm** [karafka/waterdrop#326]
Hi! I was following [this thread](https://github.com/appsignal/rdkafka-ruby/pull/242) and was interested to see if librdkafka had any impact on our message production.

The version of karafka-rdkafka I have installed includes: 

```ruby
module Rdkafka
  VERSION = "0.12.1"
  LIBRDKAFKA_VERSION = "2.0.2"
  LIBRDKAFKA_SOURCE_SHA256 = "f321bcb1e015a34114c83cf1aa7b99ee260236aab096b85c003170c90a47ca9d"
end
```

So I was feeling fairly sure we'd be using librdkafka 2.0.2. But when I turned the librdkafka debug flags all the way up (`LIBRDKAFKA_DEBUG_FLAGS=all`), I'm seeing librdkafka 1.9 referenced. Here's an example log line.

```
rdkafka: [thrd:app]: librdkafka v1.9.0 (0x10900ff) waterdrop#producer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer,http,oidc, GCC GXX PKGCONFIG OSXLD LIBDL PLUGINS ZLIB SSL SASL_CYRUS ZSTD CURL HDRHISTOGRAM LZ4_EXT SYSLOG RAPIDJSON SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER OAUTHBEARER_OIDC CRC32C_HW, debug 0xfffff)
```

I was wondering if you had insight into this, or if I was doing something wrong. We also have appsignal/rdkafka-ruby installed in the same test environment, so I'm wondering if we should be making sure to only use appsignal/rdkafka-ruby or karafka/rdkafka-ruby but not both in the same process/bundle. 

Thanks for reading! Appreciate the libraries.

**Comment by mensfeld** [comment]
@samsm for most recent version of waterdrop:

```ruby
D, [2023-03-01T15:23:30.233421 #3415417] DEBUG -- : rdkafka: [thrd:app]: librdkafka v2.0.2
```
It uses the correct one. Karafka and Waterdrop do not use `rdkafka-ruby` but `karafka-rdkafka`. It's a fork that includes some updates, performance patches (some in waterdrop and karafka) and is battle tested and stress tested against Karafka and WaterDrop to ensure it operates as expected in scale and with expected stability.

**Comment by samsm** [comment]
Waterdrop 2.4.11.

Got it, the "last wins" explanation makes sense. 👍 
Suspected it might be that. Thanks for the help!

**Comment by mensfeld** [comment]
anytime :)

**Comment by mensfeld** [comment]
@samsm on the same note I would  appreciate if you could share results of your investigation.

Also please note that WaterDrop includes metadata cache for partitioner, hence if you use partition key and not use waterdrop but use rdkafka, it's worth monitoring the cluster CPU utilization as this cache saves millions of metadata queries.

**Comment by samsm** [comment]
We ran some tests, sent/received a bunch of messages and saw nothing concerning :-)
