### ISSUE TITLE
`karafka-rdkafka` is allowed to be less than `0.12.3` with most recent WaterDrop version

### ISSUE THREAD

**Issue by hunzinker** [karafka/waterdrop#350]
Hi - I noticed this exception after upgrading `karafka v2.1.3` and `waterdrop v2.5.3`:

```
/gems/ruby/3.2.0/gems/waterdrop-2.5.3/lib/waterdrop/instrumentation/callbacks/delivery.rb:50:in `instrument_acknowledged': undefined method `topic_name' for #<Rdkafka::Producer::DeliveryReport:0x00007f6ca8051358 @partition=0, @offset=1, @error=0> (NoMethodError)

topic: delivery_report.topic_name
```

Downgrading the gems to `karafka v2.1.1` and `waterdrop v2.5.2` removed the exception. It appears to be related to the latest version release after inspecting the CHANGELOGs. Before I dig in I wanted to drop a note to see if this is a known issue?

Thanks

**Comment by mensfeld** [comment]
That is weird. Did you upgrade karafka-core and karafka-rdkafka alongside?

**Comment by mensfeld** [comment]
My wild guess is, that the constraint on `karafka-rdkafka` is not ported correctly and that you are running something less than `0.12.3` which is the minimum. Can you please try with `0.12.3` and if all good I will look into fixing dependency meanwhile?

**Comment by mensfeld** [comment]
Yeah I think it's that. When I use example app with `karafka-rdkafka` `0.12.3` it works. I dunno why it allowed you to run it with `0.12.2` :thinking: 

I was able to reproduce it. Please upgrade `karafka-rdkafka` and I will try to ask Bundler ppl tomorrow how to fix the dependency enforcement.

**Comment by mensfeld** [comment]
@hunzinker I will keep this open as a reference to fix the dependency chain.

**Comment by jcbwlkr** [comment]
@mensfeld I am having this issue

```
Traceback (most recent call last):
        9: from /Users/jwalker/.rvm/gems/ruby-2.7.6@braavos/gems/rdkafka-0.12.0/lib/rdkafka/producer/client.rb:9:in `block in initialize'
        8: from /Users/jwalker/.rvm/gems/ruby-2.7.6@braavos/gems/rdkafka-0.12.0/lib/rdkafka/producer/client.rb:9:in `loop'
        7: from /Users/jwalker/.rvm/gems/ruby-2.7.6@braavos/gems/rdkafka-0.12.0/lib/rdkafka/producer/client.rb:10:in `block (2 levels) in initialize'
        6: from /Users/jwalker/.rvm/gems/ruby-2.7.6@braavos/gems/rdkafka-0.12.0/lib/rdkafka/producer/client.rb:10:in `rd_kafka_poll'
        5: from /Users/jwalker/.rvm/gems/ruby-2.7.6@braavos/gems/rdkafka-0.12.0/lib/rdkafka/callbacks.rb:84:in `block in <module:Callbacks>'
        4: from /Users/jwalker/.rvm/gems/ruby-2.7.6@braavos/gems/rdkafka-0.12.0/lib/rdkafka/callbacks.rb:100:in `call'
        3: from /Users/jwalker/.rvm/gems/ruby-2.7.6@braavos/gems/rdkafka-0.12.0/lib/rdkafka/config.rb:282:in `call_delivery_callback'
        2: from /Users/jwalker/.rvm/gems/ruby-2.7.6@braavos/gems/rdkafka-0.12.0/lib/rdkafka/producer.rb:165:in `call_delivery_callback'
        1: from /Users/jwalker/.rvm/gems/ruby-2.7.6@braavos/gems/waterdrop-2.6.0/lib/waterdrop/instrumentation/callbacks/delivery.rb:23:in `call'
/Users/jwalker/.rvm/gems/ruby-2.7.6@braavos/gems/waterdrop-2.6.0/lib/waterdrop/instrumentation/callbacks/delivery.rb:50:in `instrument_acknowledged': undefined method `topic_name' for #<Rdkafka::Producer::DeliveryReport:0x00007ffbb3bbab28> (NoMethodError)

```

My gems are

```
    waterdrop (2.6.0)
    karafka-core (2.0.13)
    karafka-rdkafka (0.12.3)
    rdkafka (0.12.0)
```

I'm not sure what i'm doing wrong

**Comment by mensfeld** [comment]
>     karafka-rdkafka (0.12.3)
>     rdkafka (0.12.0)

You **cannot** have both. One conflicts with another. Please only use `karafka-rdkafka` and all will be fixed. `rdkafka` overwrites what `karafka-rdkafka` does.

**Comment by jcbwlkr** [comment]
That fixed it. Thanks so much, @mensfeld!
