### ISSUE TITLE
NoMethodError: undefined method `name' for #<Rdkafka::Producer:0x0000562d3d2e5d18>

### ISSUE THREAD

**Issue by RachelSa** [karafka/waterdrop#365]
The following error occurs when setting client:

```NoMethodError: undefined method `name' for #<Rdkafka::Producer:0x0000562d3d2e5d18>
from /usr/local/bundle/gems/waterdrop-2.6.3/lib/waterdrop/producer.rb:105:in `block in client'```

**Comment by mensfeld** [comment]
@RachelSa can you upgrade `karafka-core` and `karafka-rdkafka` alongside `waterdrop`? I have no idea why the ranges do not work as expected and I guess I will have to consult with rubygems devs. Once you upgrade `karafka-rdkafka` to `0.13.2` this will go away.

**Comment by mensfeld** [comment]
If that helps, please close this issue :pray:

**Comment by mensfeld** [comment]
general upgrade guidance: https://karafka.io/docs/Upgrading/
