### ISSUE TITLE
Potential message loss in async mode

### ISSUE THREAD

**Issue by dmaze** [karafka/waterdrop#50]
https://github.com/karafka/waterdrop/blob/master/lib/water_drop/async_producer.rb#L18 calls `DeliveryBoy.deliver_async` on outbound messages.  But, if you're producing messages faster than the framework or the network can send them off, https://github.com/zendesk/delivery_boy/blob/master/lib/delivery_boy.rb#L37 will drop them.

It would be nice if there were a config option to `deliver_async!` so that the application could respond to the buffer-full state.

**Comment by mensfeld** [comment]
You are right. Would a ```raise_on_buffer_overflow``` flag wuld be enough?

**Comment by mensfeld** [comment]
@dmaze https://github.com/karafka/waterdrop/pull/51/files
Note - that even with raising, WaterDrop will retry to deliver 3 times by default - but this is desired.

**Comment by mensfeld** [comment]
Can't wait. Will merge. Meanwhile if you have any other thoughts, just ping me!
