### ISSUE TITLE
Cannot send message with producer

### ISSUE THREAD

**Issue by cxk280** [karafka/waterdrop#53]
I have followed the example app instructions and gotten the Ping Pong game to work. However, when I try to send a message with either `WaterDrop::SyncProducer.call('message', topic: 'my-topic')` or `WaterDrop::AsyncProducer.call('message', topic: 'my-topic')`, I receive the error `syntax error near unexpected token 'message','`.

How do I resolve this?

**Comment by mensfeld** [comment]
Where do you receive this error? In waterdrop or in Karafka? I will assume that in Karafka. If so it simply means that you don't send a hash. Karafka assumes that you send hash with data. You can change that by implementing a custom parser. Please reopen if you get this error from within waterdrop.

**Comment by mensfeld** [comment]
Hey @cxk280, did I solve your problem? A bit more of an explanation: default Karafka parser assumes that what you are sending is a JSON hash (not a JSONed string or anything else). If you want to send something else, you just need to implement a custom parser as stated here: https://github.com/karafka/karafka/wiki/Parsers

**Comment by cxk280** [comment]
I've got some other stuff that came up, so I'm going to take another look
at this next week. I really appreciate your attentiveness. Your explanation
certainly sounds right.
